<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK6rL7Hs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK6rL7Hs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK6rL7Hs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK6rL7Hs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerK6rL7Hs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'K6rL7Hs',
    'container.build_id' => 'd7b7c4d2',
    'container.build_time' => 1562923692,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK6rL7Hs');
