<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDlssTFi\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDlssTFi/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDlssTFi.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDlssTFi\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDlssTFi\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DlssTFi',
    'container.build_id' => '705a30cc',
    'container.build_time' => 1552508431,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDlssTFi');
