<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPu9upBg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPu9upBg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPu9upBg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPu9upBg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPu9upBg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Pu9upBg',
    'container.build_id' => 'ace8bdfd',
    'container.build_time' => 1556454094,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPu9upBg');
