index:
    path: /
    controller: App\Controller\GeneralController::indexAction

twig_page:
    path: /twig-page
    controller: App\Controller\GeneralController::twigPageAction

razor_in_twig_page:  
    path: /razor-in-twig-page
    controller: App\Controller\GeneralController::razorInTwigPageAction